version: "3"
volumes:
  postgres-data:
services:
  smallurl:
    image: postus
    networks:
      - default
    volumes:
      - ./app-log:/app/app-log
      - ./config/docker-config.yaml:/config.yaml
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/config.yaml
    depends_on:
      - url-bd
    restart: on-failure
  url-bd:
    image: postgres:16
    expose:
      - "5432"
    command: "postgres -c shared_preload_libraries='pg_stat_statements'"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
networks:
  default:
    driver: bridge
